//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onlinemarketingEntities : DbContext
    {
        public onlinemarketingEntities()
            : base("name=onlinemarketingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminn> adminn { get; set; }
        public virtual DbSet<category> category{ get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
    }
}
